import os
import threading
from contextlib import contextmanager

import psycopg


DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://localhost/news_parser",
)

SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS posts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        news_title TEXT NOT NULL,
        news_text TEXT NOT NULL,
        university_name TEXT NOT NULL,
        news_date TEXT NOT NULL,
        news_img BYTEA,
        deleted INTEGER NOT NULL DEFAULT 0
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS comments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        post_id BIGINT NOT NULL,
        nick TEXT NOT NULL,
        text TEXT NOT NULL,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS post_views (
        post_id BIGINT NOT NULL,
        voter_id UUID NOT NULL,
        PRIMARY KEY (post_id, voter_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS post_likes (
        post_id BIGINT NOT NULL,
        voter_id UUID NOT NULL,
        PRIMARY KEY (post_id, voter_id)
    )
    """,
)

_schema_lock = threading.Lock()
_schema_initialized = False


def initialize_schema(connection):
    global _schema_initialized
    if _schema_initialized:
        return
    with _schema_lock:
        if _schema_initialized:
            return
        with connection.transaction():
            for statement in SCHEMA_STATEMENTS:
                connection.execute(statement)
        _schema_initialized = True


@contextmanager
def get_connection():
    with psycopg.connect(DATABASE_URL) as connection:
        initialize_schema(connection)
        yield connection
